-- MySQL Script generated by MySQL Workbench
-- 12/24/18 22:46:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sch_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_user` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sch_userinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_userinfo` (
  `nickname` VARCHAR(50) NOT NULL,
  `sex` INT NOT NULL,
  `school` VARCHAR(100) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `brithday` DATE NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `area` VARCHAR(100) NOT NULL,
  `token` VARCHAR(200) NULL,
  `poto` VARCHAR(100) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `identity` INT NOT NULL,
  INDEX `fk_sch_userinfo_sch_user_idx` (`username` ASC),
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_sch_userinfo_sch_user`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_classfiy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_classfiy` (
  `classname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`classname`),
  UNIQUE INDEX `calssname_UNIQUE` (`classname` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_article` (
  `arti_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `article` MEDIUMTEXT NOT NULL,
  `starttime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `classname` VARCHAR(20) NOT NULL,
  `poweer` INT NOT NULL,
  PRIMARY KEY (`arti_id`),
  UNIQUE INDEX `arti_id_UNIQUE` (`arti_id` ASC),
  INDEX `fk_sch_article_sch_user1_idx` (`username` ASC),
  INDEX `fk_sch_article_sch_classfiy1_idx` (`classname` ASC),
  CONSTRAINT `fk_sch_article_sch_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_article_sch_classfiy1`
    FOREIGN KEY (`classname`)
    REFERENCES `mydb`.`sch_classfiy` (`classname`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_respond_arti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_respond_arti` (
  `resp_id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `starttime` DATETIME NOT NULL,
  `arti_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`resp_id`),
  UNIQUE INDEX `resp_id_UNIQUE` (`resp_id` ASC),
  INDEX `fk_sch_respond_sch_article1_idx` (`arti_id` ASC),
  INDEX `fk_sch_respond_sch_user1_idx` (`username` ASC),
  CONSTRAINT `fk_sch_respond_sch_article1`
    FOREIGN KEY (`arti_id`)
    REFERENCES `mydb`.`sch_article` (`arti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_respond_sch_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_pre_resp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_pre_resp` (
  `pre_id` INT NOT NULL AUTO_INCREMENT,
  `resp_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pre_id`),
  UNIQUE INDEX `resp_id_UNIQUE` (`pre_id` ASC),
  INDEX `fk_sch_pre_resp_sch_respond1_idx` (`resp_id` ASC),
  INDEX `fk_sch_pre_resp_sch_user1_idx` (`username` ASC),
  CONSTRAINT `fk_sch_pre_resp_sch_respond1`
    FOREIGN KEY (`resp_id`)
    REFERENCES `mydb`.`sch_respond_arti` (`resp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_pre_resp_sch_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sch_attention`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_attention` (
  `atten_id` INT NOT NULL AUTO_INCREMENT,
  `username_ed` VARCHAR(20) NOT NULL,
  `username_att` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`atten_id`),
  UNIQUE INDEX `atten_id_UNIQUE` (`atten_id` ASC),
  INDEX `fk_sch_attention_sch_user1_idx` (`username_ed` ASC),
  INDEX `fk_sch_attention_sch_user2_idx` (`username_att` ASC),
  CONSTRAINT `fk_sch_attention_sch_user1`
    FOREIGN KEY (`username_ed`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_attention_sch_user2`
    FOREIGN KEY (`username_att`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sch_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_admin` (
  `id` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sch_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_message` (
  `mess_id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `username_ed` VARCHAR(20) NOT NULL,
  `username_mes` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`mess_id`),
  UNIQUE INDEX `mess_id_UNIQUE` (`mess_id` ASC),
  INDEX `fk_sch_message_sch_user1_idx` (`username_ed` ASC),
  INDEX `fk_sch_message_sch_user2_idx` (`username_mes` ASC),
  CONSTRAINT `fk_sch_message_sch_user1`
    FOREIGN KEY (`username_ed`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_message_sch_user2`
    FOREIGN KEY (`username_mes`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_dynamic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_dynamic` (
  `dynamic_id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `starttime` DATETIME NOT NULL,
  `sch_user_username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`dynamic_id`),
  UNIQUE INDEX `dynamic_id_UNIQUE` (`dynamic_id` ASC),
  INDEX `fk_sch_dynamic_sch_user1_idx` (`sch_user_username` ASC),
  CONSTRAINT `fk_sch_dynamic_sch_user1`
    FOREIGN KEY (`sch_user_username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_pre_dynam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_pre_dynam` (
  `pre_id` INT NOT NULL AUTO_INCREMENT,
  `dynamic_id` INT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`pre_id`),
  UNIQUE INDEX `pre_id_UNIQUE` (`pre_id` ASC),
  INDEX `fk_sch_pre_dynam_sch_dynamic1_idx` (`dynamic_id` ASC),
  INDEX `fk_sch_pre_dynam_sch_user1_idx` (`username` ASC),
  CONSTRAINT `fk_sch_pre_dynam_sch_dynamic1`
    FOREIGN KEY (`dynamic_id`)
    REFERENCES `mydb`.`sch_dynamic` (`dynamic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_pre_dynam_sch_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sch_respond_dyna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_respond_dyna` (
  `resp_id` INT NOT NULL AUTO_INCREMENT,
  `content` MEDIUMTEXT NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `dynamic_id` INT NOT NULL,
  PRIMARY KEY (`resp_id`),
  UNIQUE INDEX `resp_id_UNIQUE` (`resp_id` ASC),
  INDEX `fk_sch_respond_dyna_sch_user1_idx` (`username` ASC),
  INDEX `fk_sch_respond_dyna_sch_dynamic1_idx` (`dynamic_id` ASC),
  CONSTRAINT `fk_sch_respond_dyna_sch_user1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`sch_user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_respond_dyna_sch_dynamic1`
    FOREIGN KEY (`dynamic_id`)
    REFERENCES `mydb`.`sch_dynamic` (`dynamic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`sch_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sch_images` (
  `imag_id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(100) NOT NULL,
  `dynamic_id` INT NULL,
  `arti_id` INT NULL,
  PRIMARY KEY (`imag_id`),
  UNIQUE INDEX `imag_id_UNIQUE` (`imag_id` ASC),
  INDEX `fk_sch_images_sch_dynamic1_idx` (`dynamic_id` ASC),
  INDEX `fk_sch_images_sch_article1_idx` (`arti_id` ASC),
  CONSTRAINT `fk_sch_images_sch_dynamic1`
    FOREIGN KEY (`dynamic_id`)
    REFERENCES `mydb`.`sch_dynamic` (`dynamic_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sch_images_sch_article1`
    FOREIGN KEY (`arti_id`)
    REFERENCES `mydb`.`sch_article` (`arti_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
